name: Update build in production

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_production:
    runs-on: debian-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Upload the build folder to the bluehost server
        run: |
          secret=keR[+r]S*K^Gwa1%hk
          ls -lah
