name: Update build in production

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Upload the build folder to the bluehost server
        run: |
          secret=keR[+r]S*K^Gwa1%hk
          ls -lah
          #ftp -n ftp.backupte4.rsyncbackup.info << EOF
          #quote USER bapte
          #quote PASS b2p7Ua2
          #put somefile
          #quit
          #EOF
